apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  generation: 1
  name: analysis-results-qa
  selfLink: /apis/apps.openshift.io/v1/namespaces/flint-qa/deploymentconfigs/analysis-results-qa
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    deployment-config.name: analysis-results-qa
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment-config.name: analysis-results-qa
    spec:
      containers:
      - env:
        - name: AR_PORT
          value: "8080"
        - name: AR_DB_URL
          value: jdbc:postgresql://flintdb:5432/aresults
        - name: AR_DB_USER
          valueFrom:
            secretKeyRef:
              key: AR_DB_USER
              name: analysis-results-db-qa
        - name: AR_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: AR_DB_PASSWORD
              name: analysis-results-db-qa
        - name: AR_MIGRATION_ENABLED
          value: "true"
        - name: AR_DATA_MAX_RESULTS
          value: "10"
        - name: AR_LOG_INFO
          value: info
        image: docker-registry.default.svc:5000/analysis-results-dev/analysis-results-dev:qa
        imagePullPolicy: Always
        name: default-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
