apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: passit
  template: passit
message: 'The following service(s) have been created in your project: ${NAME}.'
metadata:
  annotations:
    description: Passit - the open source Password Manager
    openshift.io/display-name: Passit PostgreSQL
    openshift.io/documentation-url: https://passit.io
    openshift.io/provider-display-name: Burke Software and Consulting
    template.openshift.io/bindable: "false"
  creationTimestamp: 2019-12-12T18:59:26Z
  name: passit
  namespace: template
  resourceVersion: "92639490"
  selfLink: /apis/template.openshift.io/v1/namespaces/template/templates/passit
  uid: 84c15909-1d11-11ea-991c-0050569a1f76
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}
  stringData:
    database-password: ${DATABASE_PASSWORD}
    database-user: ${DATABASE_USER}
    django-secret-key: ${DJANGO_SECRET_KEY}
    email-url: ${EMAIL_URL}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Passit django backend + Angular frontend
      service.alpha.openshift.io/dependencies: '[{"name": "${DATABASE_SERVICE_NAME}",
        "kind": "Service"}]'
    name: ${NAME}
  spec:
    ports:
    - name: web
      port: 8080
      targetPort: 8080
    selector:
      name: ${NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    tls:
      termination: edge
    to:
      kind: Service
      name: ${NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Stable Passit docker image
    name: ${NAME}
  spec:
    tags:
    - from:
        kind: DockerImage
        name: passit/passit:stable
      name: latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Defines how to deploy the passit docker image
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 0%
        maxUnavailable: 100%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - env:
          - name: DATABASE_SERVICE_NAME
            value: ${DATABASE_SERVICE_NAME}
          - name: DATABASE_NAME
            value: ${DATABASE_NAME}
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: ${NAME}
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: ${NAME}
          - name: APP_CONFIG
            value: ${APP_CONFIG}
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: django-secret-key
                name: ${NAME}
          - name: IS_DEBUG
            value: "False"
          - name: EMAIL_URL
            valueFrom:
              secretKeyRef:
                key: email-url
                name: ${NAME}
          - name: FROM_EMAIL
            value: ${FROM_EMAIL}
          - name: EMAIL_CONFIRMATION_HOST
            value: ${APPLICATION_DOMAIN}
          - name: IS_PRIVATE_ORG_MODE
            value: ${IS_PRIVATE_ORG_MODE}
          - name: ENVIRONMENT
            value: production
          image: ' '
          name: passit
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - passit
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: passit
- description: The OpenShift Namespace where the ImageStream resides.
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: openshift
- description: Maximum amount of memory the Passit django container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: The exposed hostname that will route to the Django service, if left
    blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- displayName: Database Service Name
  name: DATABASE_SERVICE_NAME
  required: true
  value: postgresql
- displayName: Database Name
  name: DATABASE_NAME
  required: true
  value: default
- displayName: Database Username
  name: DATABASE_USER
  required: true
  value: django
- displayName: Database User Password
  name: DATABASE_PASSWORD
  required: true
- description: Set this to a long random string.
  displayName: Django Secret Key
  from: '[\w]{50}'
  generate: expression
  name: DJANGO_SECRET_KEY
- displayName: EMAIL SMTP authentication URL. Defaults only to console mail (does
    not send email). Example smtp://postmaster@passit.io:password@smtp.example.com
  name: EMAIL_URL
  value: consolemail://
- displayName: Is this a private server where all user contacts should be shared with
    other users? Such as a company's internal passit server. If you don't know it's
    fine to set to false.
  name: IS_PRIVATE_ORG_MODE
  required: true
  value: "False"
