apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: flint-qaplan
  template: flint-qaplan
message: 'The following service(s) have been created in your project: ${NAME}.'
metadata:
  annotations:
    description: FLINT
    openshift.io/display-name: flint-qaplan
    openshift.io/documentation-url: https://gnivc.ru
    openshift.io/provider-display-name: GNIVC
    template.openshift.io/bindable: "false"
  creationTimestamp: null
  name: flint-qaplan
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}
  stringData:
    qap-service-user: ${QAP_SERVICE_USER}
    qap-service-password: ${QAP_SERVICE_PASSWORD}
    qaplan-db-user: ${QAP_DB_USER}
    qaplan-db-password: ${QAP_DB_PASSWORD}
    bum-user: ${QAP_BUM_USER}
    bum-password: ${QAP_BUM_PASSWORD}
    incident-service-user: ${QAP_INCIDENT_USER}
    incident-service-password: ${QAP_INCIDENT_PASSWORD}
    
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name": "${SERVICE_NAME}", "kind":
        "Service"}]'
    name: ${NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: ${NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 0%
        maxUnavailable: 100%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - env:
          - name: QAP_PORT
            value: ${QAP_PORT}
          - name: QAP_SERVICE_USER
            valueFrom:
              secretKeyRef:
                key: qap-service-user
                name: ${NAME}
          - name: QAP_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: qap-service-password
                name: ${NAME}
          - name: QAP_DB_URL
            value: ${QAP_DB_URL}
          - name: QAP_DB_USER
            valueFrom:
              secretKeyRef:
                key: qaplan-db-user
                name: ${NAME}
          - name: QAP_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: qaplan-db-password
                name: ${NAME}
          - name: QAP_BUM_URL
            value: ${QAP_BUM_URL}
          - name: QAP_BUM_USER
            valueFrom:
              secretKeyRef:
                key: bum-user
                name: ${NAME}
          - name: QAP_BUM_PASSWORD
            valueFrom:
              secretKeyRef:
                key: bum-password
                name: ${NAME}
          - name: QAP_AC_WF_NAME
            value: ${QAP_AC_WF_NAME}
          - name: QAP_AUTH_URL
            value: ${QAP_AUTH_URL}
          - name: QAP_INCIDENT_URL
            value: ${QAP_INCIDENT_URL}
          - name: QAP_INCIDENT_USER
            valueFrom:
              secretKeyRef:
                key: incident-service-user
                name: ${NAME}
          - name: QAP_INCIDENT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: incident-service-password
                name: ${NAME}
          image: ${NAME}
          name: ${NAME}
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name assigned to all of the objects defined in this template. For successful deployment there have to be imagestream with same name in chosen namespace.
  displayName: Name
  name: NAME
  required: true
  value: qaplan
- description: Maximum amount of memory the service-ac container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 1Gi
- description: The exposed hostname that will route to the service-ac, if left blank
    a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- displayName: Service Name
  name: SERVICE_NAME
  required: true
  value: qaplan
- displayName: QAP_PORT
  name: QAP_PORT
  value: "8080"
- displayName: QAP_DB_URL
  name: QAP_DB_URL
  value: 'jdbc:postgresql://flintdb:5432/qaplan_services'
- displayName: Database Username
  name: QAP_DB_USER
  required: true
  value: ac
- displayName: Database User Password
  name: QAP_DB_PASSWORD
  required: true
  value: ac
- displayName: QAP_SERVICE_USER
  name: QAP_SERVICE_USER
  value: "user"
- displayName: QAP_SERVICE_PASSWORD
  name: QAP_SERVICE_PASSWORD
  value: "password"
- displayName: QAP_BUM_URL
  name: QAP_BUM_URL
  value: 'http://bum:8080'
- displayName: QAP_BUM_USER 
  name: QAP_BUM_USER
  value: "user"
- displayName: QAP_BUM_PASSWORD 
  name: QAP_BUM_PASSWORD
  value: "password"
- displayName: QAP_AC_WF_NAME 
  name: QAP_AC_WF_NAME
  value: 'wf_AC_flint_dev_incident_manual_tsk_loader'
- displayName: QAP_AUTH_URL
  name: QAP_AUTH_URL
  value: 'http://auth-service:8080'
- displayName: QAP_INCIDENT_URL
  name: QAP_INCIDENT_URL
  value: 'http://incident-core:8080'
- displayName: QAP_INCIDENT_USER
  name: QAP_INCIDENT_USER
  value: "user"
- displayName: QAP_INCIDENT_PASSWORD
  name: QAP_INCIDENT_PASSWORD
  value: "password"
