apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: services-ac
  template: services-ac
message: 'The following service(s) have been created in your project: ${NAME}.'
metadata:
  annotations:
    description: FLINT
    openshift.io/display-name: services-ac
    openshift.io/documentation-url: https://gnivc.ru
    openshift.io/provider-display-name: GNIVC
    template.openshift.io/bindable: "false"
  creationTimestamp: null
  name: flint-services-ac
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}
  stringData:
    ac-db-password: ${AC_DB_PASSWORD}
    ac-db-user: ${AC_DB_USER}
    ac-incident-db-pwd: ${AC_INCIDENT_DB_PWD}
    ac-incident-db-user: ${AC_INCIDENT_DB_USER}
    bum-password: ${AC_MMS_PASSWORD}
    bum-user: ${AC_MMS_USER}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name": "${SERVICE_NAME}", "kind":
        "Service"}]'
    name: ${NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080-tcp
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443-tcp
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778-tcp
    selector:
      name: ${NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    to:
      kind: Service
      name: ${NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 0%
        maxUnavailable: 100%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - env:
          - name: AC_PORT
            value: "8080"
          - name: AC_DB_URL
            value: jdbc:postgresql://flintdb:5432/ac
          - name: AC_DB_USER
            valueFrom:
              secretKeyRef:
                key: ac-db-user
                name: ${NAME}
          - name: AC_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: ac-db-password
                name: ${NAME}
          - name: SERVICE_NAME
            value: ${SERVICE_NAME}
          - name: AC_MIGRATION_ENABLED
            value: "true"
          - name: AC_CE_BUM_TABLE_META
            value: "86400000"
          - name: AC_CE_SQL_TABLE_META
            value: "86400000"
          - name: AC_CSUD_HOST_NAME
            value: http://10.250.25.16:9901
          - name: AC_NAME_OF_SUBSYSTEM
            value: flint-ac
          - name: AC_AR_HOST
            value: http://analysis-results-qa:8080/analysis-results
          - name: AC_LAUNCH_WFNMEUNQ
            value: tmp_wf_AC_flint_manual_tsk_loader
          - name: AC_LAUNCH_SPARK_MASTER
            value: local
          - name: AC_LAUNCH_RPE
            value: "false"
          - name: AC_LAUNCH_E_METASTORE
            value: thrift://adp-eiap-hnn1.adp.local:9083
          - name: AC_LAUNCH_METASTORE
            value: thrift://adp-eiap-hnn1.adp.local:9083
          - name: AC_MMS_HOST_NAME
            value: http://bum:8080
          - name: AC_MMS_USER
            valueFrom:
              secretKeyRef:
                key: bum-user
                name: ${NAME}
          - name: AC_MMS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: bum-password
                name: ${NAME}
          - name: AC_INCIDENT_LIMIT
            value: "10"
          - name: AC_INCIDENT_DB_URL
            value: jdbc:postgresql://flintdb:5432/aresults
          - name: AC_INCIDENT_DB_USER
            valueFrom:
              secretKeyRef:
                key: ac-incident-db-user
                name: ${NAME}
          - name: AC_INCIDENT_DB_PWD
            valueFrom:
              secretKeyRef:
                key: ac-incident-db-pwd
                name: ${NAME}
          - name: AC_AUTH_URL
            value: http://auth-service-qa:8080
          - name: GC_MAX_METASPACE_SIZE
            value: "256"
          image: ${NAME}
          name: ${NAME}
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name assigned to all of the objects defined in this template. For successful deployment there have to be imagestream with same name in chosen namespace.
  displayName: Name
  name: NAME
  required: true
  value: services-ac
- description: Maximum amount of memory the service-ac container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 512Mi
- description: The exposed hostname that will route to the service-ac, if left blank
    a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- displayName: Service Name
  name: SERVICE_NAME
  required: true
  value: services-ac
- displayName: AC_PORT
  name: AC_PORT
  value: "8080"
- displayName: AC_DB_URL
  name: AC_DB_URL
  value: jdbc:postgresql://flintdb:5432/ac
- displayName: Database Username
  name: AC_DB_USER
  required: true
  value: ac
- displayName: Database User Password
  name: AC_DB_PASSWORD
  required: true
  value: ac
- displayName: AC_MIGRATION_ENABLED
  name: AC_MIGRATION_ENABLED
  value: "true"
- displayName: AC_CE_BUM_TABLE_META
  name: AC_CE_BUM_TABLE_META
  value: "86400000"
- displayName: AC_CE_SQL_TABLE_META
  name: AC_CE_SQL_TABLE_META
  value: "86400000"
- displayName: AC_CSUD_HOST_NAME
  name: AC_CSUD_HOST_NAME
  value: http://10.250.25.16:9901
- displayName: AC_NAME_OF_SUBSYSTEM
  name: AC_NAME_OF_SUBSYSTEM
  value: flint-ac
- displayName: AC_AR_HOST
  name: AC_AR_HOST
  value: http://analysis-results-qa:8080/analysis-results
- displayName: AC_LAUNCH_WFNMEUNQ
  name: AC_LAUNCH_WFNMEUNQ
  value: tmp_wf_AC_flint_manual_tsk_loader
- displayName: AC_LAUNCH_SPARK_MASTER
  name: AC_LAUNCH_SPARK_MASTER
  value: local
- displayName: AC_LAUNCH_RPE
  name: AC_LAUNCH_RPE
  value: "false"
- displayName: AC_LAUNCH_E_METASTORE
  name: AC_LAUNCH_E_METASTORE
  value: thrift://adp-eiap-hnn1.adp.local:9083
- displayName: AC_LAUNCH_METASTORE
  name: AC_LAUNCH_METASTORE
  value: thrift://adp-eiap-hnn1.adp.local:9083
- displayName: AC_MMS_HOST_NAME
  name: AC_MMS_HOST_NAME
  value: http://bum:8080
- displayName: AC_MMS_USER
  name: AC_MMS_USER
  value: user
- displayName: AC_MMS_PASSWORD
  name: AC_MMS_PASSWORD
  value: password
- displayName: AC_INCIDENT_LIMIT
  name: AC_INCIDENT_LIMIT
  value: "10"
- displayName: AC_INCIDENT_DB_URL
  name: AC_INCIDENT_DB_URL
  value: jdbc:postgresql://flintdb:5432/aresults
- displayName: AC_INCIDENT_DB_URL
  name: AC_INCIDENT_DB_USER
  value: user
- displayName: AC_INCIDENT_DB_PWD
  name: AC_INCIDENT_DB_PWD
  value: password
- displayName: AC_AUTH_URL
  name: AC_AUTH_URL
  value: http://auth-service-qa:8080
- displayName: GC_MAX_METASPACE_SIZE
  name: GC_MAX_METASPACE_SIZE
  value: "256"
