apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: flint-services-requests
  template: flint-services-requests
message: 'The following service(s) have been created in your project: ${NAME}.'
metadata:
  annotations:
    description: FLINT
    openshift.io/display-name: flint-services-requests
    openshift.io/documentation-url: https://gnivc.ru
    openshift.io/provider-display-name: GNIVC
    template.openshift.io/bindable: "false"
  creationTimestamp: null
  name: flint-services-requests
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}
  stringData:
    services-requests-db-password: ${RS_DB_PASSWORD}
    services-requests-db-user: ${RS_DB_USER}
    qaplan-service-password: ${QAP_SERVICE_PASSWORD}
    qaplan-service-user: ${QAP_SERVICE_USER}
    services-ac-user: ${AC_SERVICE_USER}
    services-ac-password: ${AC_SERVICE_PASSWORD}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/dependencies: '[{"name": "${SERVICE_NAME}", "kind":
        "Service"}]'
    name: ${NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: ${NAME}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      name: ${NAME}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 0%
        maxUnavailable: 100%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          name: ${NAME}
        name: ${NAME}
      spec:
        containers:
        - env:
          - name: RS_PORT
            value: '8080'
          - name: RS_DB_URL
            value: 'jdbc:postgresql://flintdb:5432/requests_services'
          - name: RS_DB_USER
            valueFrom:
              secretKeyRef:
                key: services-requests-db-user
                name: ${NAME}
          - name: RS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: services-requests-db-password
                name: ${NAME}
          - name: QAP_SERVICE_ROOT_URL
            value: 'http://qaplan-qa:8080'
          - name: QAP_SERVICE_USER
            valueFrom:
              secretKeyRef:
                key: qaplan-service-user
                name: ${NAME}
          - name: QAP_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: qaplan-service-password
                name: ${NAME}
          - name: RS_AUTH_URL
            value: 'http://auth-service-qa:8080'
          - name: AC_SERVICE_ROOT_URL
            value: 'http://services-ac-qa:8080'
          - name: AC_SERVICE_USER
            valueFrom:
              secretKeyRef:
                key: services-ac-user
                name: ${NAME}
          - name: AC_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: services-ac-password
                name: ${NAME}
          image: ${NAME}
          name: ${NAME}
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${NAME}:latest
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name assigned to all of the objects defined in this template. For successful deployment there have to be imagestream with same name in chosen namespace.
  displayName: Name
  name: NAME
  required: true
  value: services-requests
- description: Maximum amount of memory the service-ac container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 1Gi
- description: The exposed hostname that will route to the service-ac, if left blank
    a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- displayName: Service Name
  name: SERVICE_NAME
  required: true
  value: services-requests
- displayName: RS_PORT
  name: RS_PORT
  value: "8080"
- displayName: RS_DB_URL
  name: RS_DB_URL
  value: 'jdbc:postgresql://flintdb:5432/requests_services'
- displayName: Database Username
  name: RS_DB_USER
  required: true
  value: requests_services
- displayName: Database User Password
  name: RS_DB_PASSWORD
  required: true
  value: requests_services
- displayName: QAP_SERVICE_ROOT_URL
  name: QAP_SERVICE_ROOT_URL
  value: 'http://qaplan:8080'
- displayName: QAP_SERVICE_USER
  name: QAP_SERVICE_USER
  value: "user"
- displayName: QAP_SERVICE_PASSWORD
  name: QAP_SERVICE_PASSWORD
  value: "pa$$w0rd"
- displayName: RS_AUTH_URL
  name: RS_AUTH_URL
  value: 'http://auth-service:8080'
- displayName: AC_SERVICE_ROOT_URL
  name: AC_SERVICE_ROOT_URL
  value: 'http://services-ac:8080'
- displayName: AC_SERVICE_USER
  name: AC_SERVICE_USER
  value: 'user'
- displayName: AC_SERVICE_PASSWORD 
  name: AC_SERVICE_PASSWORD
  value: 'pa$$w0rd'
